[package]
name = "bevy_mod_picking"
version = "0.4.1-alpha.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A 3D mouse picking and raycasting plugin for Bevy."
repository = "https://github.com/aevyrie/bevy_mod_picking/"
keywords = ["gamedev", "picking", "bevy", "raycast"]
categories = ["game-engines", "rendering"]

[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render"] }
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = ["render"] }
bevy_mod_raycast = "0.2"
#bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast", branch = "master" }

[features]
ex = ["bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/bevy_gltf", "bevy/x11"]

[[example]]
name = "3d_scene"
required-features = ["ex"]

[[example]]
name = "deselection"
required-features = ["ex"]

[[example]]
name = "events"
required-features = ["ex"]

[[example]]
name = "stress_test"
required-features = ["ex"]
